import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const kantPro = Libre_Franklin({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Godly Productions Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen p-5 ${kantPro.className}`}
      >
        <Navbar/>
        <div className="bg-black rounded-xl text-white p-8 grow">
          {children}
        </div>
      </body>
    </html>
  );
}
