import type { Metadata } from "next";
import { Kantumruy_Pro } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const kantPro = Kantumruy_Pro({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Godly Productions Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kantPro.className} antialiased m-4`}
      >
        <Navbar/>
        <div className="bg-black rounded-xl text-white p-4">
          {children}
        </div>
      </body>
    </html>
  );
}
