import type { Metadata } from "next";
import { Libre_Franklin } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import HeaderMenuMobile from "@/components/HeaderMenuMobile";
import { GoogleAnalytics } from "@next/third-parties/google";

const kantPro = Libre_Franklin({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Godly Productions Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`flex flex-col min-h-screen p-2 sm:p-5 ${kantPro.className}`}
      >
        <div className="fade-in duration-150">
          <Navbar/>
          <HeaderMenuMobile/>

        </div>
        <div className="z-[1] relative bg-black rounded-xl text-white p-4 sm:p-8 grow">
          {children}
        </div>
      </body>
      <GoogleAnalytics gaId='G-RD6BKEXSF2'/> 
    </html>
  );
}
